### ISSUE TITLE
Great REAMDE

### ISSUE THREAD

**Issue by dancingfrog** [kixxauth/CHAP#1]
Hi,

I haven't used your module, but I just wanted to say that your explanation and pseudo code for implementing CHAP are outstanding. First time I really understood it :+1:

**Comment by kixxauth** [comment]
Thanks @dancingfrog :smile: I really appreciate that. I've only used the CHAP protocol on a few projects, but it's worked flawlessly so far. I've done it with Python as well as Node.js.
